config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/", to: "home#index"
  get "/signin", to: "sessions#new", as: :new_sessions
  post "/signin", to: "sessions#create", as: :sessions
  delete "/signout", to: "sessions#destroy", as: :destroy_sessions
  get "/menu_categories/new", to: "menu_categories#new", as: :new_menu_categories
  get "/menu_items/new", to: "menu_items#new", as: :new_menu_items
  get "/menu_items/editMenu", to: "menu_items#editMenu", as: :show_menu_items
  # post "/carts", to: "cart#create", as: :create_carts
  # put "/menu_items/i", to: "menu_items#update", as: :update_menu_items
  put "/cart_items/:id/decrement", to: "cart_items#decrement", as: :decrement_cart_items
  put "/cart_items/:id/increment", to: "cart_items#increment", as: :increment_cart_items
  post "/cart_items/:id/create" => "cart_items#create"
  get "/order_items/:id/order" => "order_items#order"
  get "/order_items" => "order_items#index"
  get "/admins" => "admins#index"

  post "/users/:id/removeAsClerk" => "users#removeAsClerk"
  post "/users/:id/makeAsClerk" => "users#makeAsClerk"
  post "/users/create_clerk" => "users#createClerk"
  get "/users/new_clerk" => "users#newClerk"

  get "/menu_categories/change_menu_category_status" => "menu_categories#allMenu"
  post "/menu_categories/:id/toggle_menu_status" => "menu_categories#toggleMenuStatus"
  get "/menu_items/:id/update_each" => "menu_items#updateEach"
  resources :menu_categories
  resources :menu_items
  resources :users
  resources :orders
  resources :order_items
  resources :carts
  resources :cart_items
  resources :admins

  # post "/menu_categories/UpdateActiveMenu" => "menu_categories#updateActiveMenu"
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  has_one_attached :item_image
  belongs_to :menu_category
  validates :name, :description, :price, presence: true
  validate :acceptable_image

  def self.get_items(id)
    where("menu_category_id = ?", id)
  end

  def self.get_item_names(id)
    where("menu_category_id = ?", id).pluck(:name, :id)
  end

  def self.get_item_values(menu_id)
    where("id = ?", menu_id).pluck(:name, :description, :price)
  end

  def acceptable_image
    return unless item_image.attached?

    unless item_image.byte_size <= 2.megabyte
      errors.add(:item_image, "is too big")
    end

    acceptable_types = ["image/jpeg", "image/png"]
    unless acceptable_types.include?(item_image.content_type)
      errors.add(:item_image, "must be a JPEG or PNG")
    end
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  # skip_before_action :verify_authenticity_token
  before_action :ensure_owner_logged_in, only: [:new, :editMenu, :create, :update, :destroy, :updateEach]

  def index
    @menu_list = MenuCategory.all
    @menu_items = MenuItem
    render "index"
  end

  def new
    @menu_list = MenuCategory.get_name
  end

  def editMenu
    @menu_list = MenuCategory.get_name
    menu_category_id = params[:menu_category_id]
    @menu_items = MenuItem.get_item_names(menu_category_id)
    item_id = params[:id]
    @item_values = MenuItem.get_item_values(item_id)
    # if params[:id]
    #   render plain: "show"
    # end
  end

  def create
    if params[:item_image] == ""
      puts "ok pic"
      flash[:error] = "Please attach item image"
    else
      new_menu_item = MenuItem.new(
        params.permit(:menu_category_id, :name, :description, :price, :item_image)
      )
      if new_menu_item.save
        flash[:error] = "Menu Item #{new_menu_item.name} has been created in #{new_menu_item.menu_category.name}!"
        redirect_to "/"
      else
        flash[:error] = new_menu_item.errors.full_messages.join("<br/>")
        redirect_to "/menu_items/new"
      end
    end
  end


  def update
    menu_item_id = params[:id]
    menu_item_name = params[:name]
    menu_item_description = params[:description]
    menu_item_price = (params[:price].to_i) * 100
    item = MenuItem.find(menu_item_id)
    item.name = menu_item_name
    item.description = menu_item_description
    item.price = menu_item_price
    if item.save
      flash[:error] = "Menu Item has been updated!"
      redirect_to "/menu_categories"
    else
      flash[:error] = "Please! fill all the fields"
      redirect_to "/menu_items/#{item.id}/update_each"
    end
  end

  def destroy
    id = params[:id]
    menu_item = MenuItem.find(id)
    menu_item.destroy
    flash[:error] = "Menu Item #{menu_item.name} in #{menu_item.menu_category.name} is Deleted!"
    redirect_to "/menu_categories"
  end

  def updateEach
    item_id = params[:id]
    @item_values = MenuItem.get_item_values(item_id)
    render "/menu_items/update"
  end
end

app/views/menu_items/editMenu.html.erb
<section class="UserNew">
  <%= form_with url: "/menu_items/editMenu", method: "get", class: "GetMenu" do |form| %>
    <div class="Form-section">
      <p class="FormInput-label">Menu Category</p>
      <%= select_tag :menu_category_id, options_for_select(@menu_list.collect { |u| u }, selected: params[:menu_category_id]), include_blank: true, onchange: "this.form.submit()" %>
    </div>
    <% if params[:menu_category_id] %>
    <div class="Form-section">
    <p class="FormInput-label">Menu Item Name</p>
    <%= select_tag(:id, options_for_select(@menu_items.collect { |u| u }, selected: params[:id]), include_blank: true, onchange: "this.form.submit()") %>
    </div>
   <div>
   <% end %>
  </div>
  <% end %>
  <%= form_with url: "/menu_items/editMenu", method: "get", class: "GetMenu" do |form| %>

  <% end %>
  <% if params[:id] %>
  <%= form_with url: "/menu_items/#{params[:id]}", method: "put" do |form| %>
    <div class="Form-section">
      <p class="FormInput-label">Menu Item Name:</p>
      <%= form.text_field :name, class: "Form-input", value: "#{@item_values[0][0]}" %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Description:</p>
      <%= form.text_area :description, class: "Form-input", value: "#{@item_values[0][1]}" %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Price:</p>
      <%= form.text_field :price, class: "Form-input", value: "#{@item_values[0][2].to_i / 100}" %>
    </div>
    <div class="Form-section">
      <%= form.submit "Save", class: "Form-submit" %>
    </div>
  <% end %>
  <% end %>






</section>

app/views/menu_items/index.html.erb
<article>
  <p>Menu Item: <%= @menu_categories.all.map { |cat| cat.name } %>
<p>Menu Item: <%= @menu_items.all.map { |item| item.name } %> </p>
<% @menu_categories.all.each do |menu| %>
  <%= menu.name %><br>
  <% @menu_items.get_items(menu.id).all.each do |item| %>
    <%= item.name %>
  <% end %>
<% end %>
</article>

app/views/menu_items/new.html.erb
<section class="UserNew">
  <%= form_with url: menu_items_path do |form| %>
    <div class="Form-section">
      <p class="FormInput-label">Menu Category Id:</p>
      <%= form.select :menu_category_id, options_for_select(@menu_list.collect { |u| u }) %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Menu Item Name:</p>
      <%= form.text_field :name, class: "Form-input" %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Description:</p>
      <%= form.text_area :description, class: "Form-input" %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Price:</p>
      <%= form.text_field :price, class: "Form-input" %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Menu Item Image:</p>
      <%= file_field_tag :item_image, direct_upload: true %>
    </div>
    <div class="Form-section">
      <%= form.submit "Add", class: "Form-submit" %>
    </div>
  <% end %>
</section>

app/views/menu_items/show.html.erb
<section class="UserNew">
  <%= form_with url: "/menu_items/edit", method: "get", class: "GetMenu" do |form| %>
    <div class="Form-section">
      <p class="FormInput-label">Menu Category</p>
      <%= select_tag :menu_category_id, options_for_select(@menu_list.collect { |u| u }, selected: params[:menu_category_id]), include_blank: true, onchange: "this.form.submit()" %>
    </div>
    <% if params[:menu_category_id] %>
    <div class="Form-section">
    <p class="FormInput-label">Menu Item Name</p>
    <%= select_tag(:id, options_for_select(@menu_items.collect { |u| u }, selected: params[:id]), include_blank: true, onchange: "this.form.submit()") %>
    </div>
   <div>
   <% end %>
  </div>
  <% end %>
  <%= form_with url: "/menu_items/edit", method: "get", class: "GetMenu" do |form| %>

  <% end %>
  <% if params[:id] %>
  <%= form_with url: "/menu_items/#{params[:id]}", method: "put" do |form| %>
    <div class="Form-section">
      <p class="FormInput-label">Menu Item Name:</p>
      <%= form.text_field :name, class: "Form-input", value: "#{@item_values[0][0]}" %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Description:</p>
      <%= form.text_area :description, class: "Form-input", value: "#{@item_values[0][1]}" %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Price:</p>
      <%= form.text_field :price, class: "Form-input", value: "#{@item_values[0][2].to_i / 100}" %>
    </div>
    <div class="Form-section">
      <%= form.submit "Save", class: "Form-submit" %>
    </div>
  <% end %>
  <% end %>






</section>

app/views/menu_items/update.html.erb
  <section class="UserNew">
  <%= form_with url: "/menu_items/#{params[:id]}", method: "put" do |form| %>
    <div class="Form-section">
      <p class="FormInput-label">Menu Item Name:</p>
      <%= form.text_field :name, class: "Form-input", value: "#{@item_values[0][0]}" %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Description:</p>
      <%= form.text_area :description, class: "Form-input", value: "#{@item_values[0][1]}" %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Price:</p>
      <%= form.text_field :price, class: "Form-input", value: "#{@item_values[0][2].to_i / 100}" %>
    </div>
    <div class="Form-section">
      <%= form.submit "Save", class: "Form-submit" %>
    </div>
  <% end %>
  </section>