config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/", to: "home#index"
  get "/signin", to: "sessions#new", as: :new_sessions
  post "/signin", to: "sessions#create", as: :sessions
  delete "/signout", to: "sessions#destroy", as: :destroy_sessions
  get "/menu_categories/new", to: "menu_categories#new", as: :new_menu_categories
  get "/menu_items/new", to: "menu_items#new", as: :new_menu_items
  get "/menu_items/editMenu", to: "menu_items#editMenu", as: :show_menu_items
  # post "/carts", to: "cart#create", as: :create_carts
  # put "/menu_items/i", to: "menu_items#update", as: :update_menu_items
  put "/cart_items/:id/decrement", to: "cart_items#decrement", as: :decrement_cart_items
  put "/cart_items/:id/increment", to: "cart_items#increment", as: :increment_cart_items
  post "/cart_items/:id/create" => "cart_items#create"
  get "/order_items/:id/order" => "order_items#order"
  get "/order_items" => "order_items#index"
  get "/admins" => "admins#index"

  post "/users/:id/removeAsClerk" => "users#removeAsClerk"
  post "/users/:id/makeAsClerk" => "users#makeAsClerk"
  post "/users/create_clerk" => "users#createClerk"
  get "/users/new_clerk" => "users#newClerk"

  get "/menu_categories/change_menu_category_status" => "menu_categories#allMenu"
  post "/menu_categories/:id/toggle_menu_status" => "menu_categories#toggleMenuStatus"
  get "/menu_items/:id/update_each" => "menu_items#updateEach"
  resources :menu_categories
  resources :menu_items
  resources :users
  resources :orders
  resources :order_items
  resources :carts
  resources :cart_items
  resources :admins

  # post "/menu_categories/UpdateActiveMenu" => "menu_categories#updateActiveMenu"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :orders
  has_one :cart

  validates :first_name, :email, :password, :phone_no, presence: true
  validates :first_name, length: { minimum: 3 }
  validate :password_requirements
  validates :email, uniqueness: { case_sensitive: false }
  validates :phone_no, uniqueness: true

  has_secure_password
  has_many :todos

  def password_requirements
    rules = {
      "is too short (minimum is 8 characters)" => /(?=.*\d)(?=.*[^A-Za-z0-9])(?=.*[a-z])(?=.*[A-Z]).{8,}/,
      "must contain at least one lowercase letter" => /[a-z]+/,
      "must contain at least one uppercase letter" => /[A-Z]+/,
      "must contain at least one digit" => /\d+/,
      "must contain at least one special character" => /[^A-Za-z0-9]+/,
    }

    rules.each do |message, regex|
      errors.add(:password, message) unless password&.match(regex)
    end
  end

  def self.clerks
    where(role: "clerk")
  end

  def self.customers
    where(role: "customer")
  end

  def self.owners
    where(role: "owner")
  end

  def self.category(role)
    if role == "clerk"
      clerks
    elsif role == "owner"
      owners
    else
      customers
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token
  skip_before_action :ensure_user_logged_in, only: [:new, :create]
  before_action :ensure_owner_logged_in, only: [:index, :removeAsClerk, :makeAsClerk, :createClerk, :newClerk]

  def index
    @users = User
    render "index"
  end

  def new
    render "users/new"
  end

  def create
    user_role = "customer"
    user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      phone_no: params[:phone_no],
      password: params[:password],
      role: user_role,
    )

    if user.save
      session[:current_user_id] = user.id
      repost("/carts")
    else
      flash[:error] = user.errors.full_messages.join("<br/>")
      redirect_to "/users/new"
    end
  end

  def removeAsClerk
    id = params[:id]
    user = User.find(id)
    user.role = "customer"
    if user.save(:validate => false)
      flash[:error] = "Role Changed"
      redirect_to "/users"
    else
      flash[:error] = "Role not Changed"
      redirect_to "/users"
    end
  end

  def makeAsClerk
    id = params[:id]
    user = User.find(id)
    user.role = "clerk"
    if user.save(:validate => false)
      flash[:error] = "Role Changed"
      redirect_to "/users"
    else
      flash[:error] = "Role not Changed"
      redirect_to "/users"
    end
  end

  def newClerk
    render "/users/new_clerk"
  end

  def createClerk
    user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      phone_no: params[:phone_no],
      password: params[:password],
      role: params[:user_role],
    )

    if user.save
      flash[:error] = "#{params[:user_role]} account with name #{params[:first_name] + " " + params[:last_name]} is created! "
      cart = Cart.new(
        date: Date.today,
        user_id: user.id,
      )
      if cart.save
        flash[:error] = "cart with id #{cart.id} is created"
        redirect_to "/menu_categories" and return
      end
    end
  end
end

app/views/users/_users.html.erb
<section>
<h1 class = "user-title"><%= role %>s </h1>
<div class="users">
  <div class="user-headings">
    <p class="user-name heading" >Full Name</p>
    <p class="user-email heading" >Email</p>
    <p class="user-phone heading" >Phone</p>
    <p class="user-role heading" >Change Role</p>
  </div>
  <% @users.category(role).all.each do |user| %>
    <div class="user">
      <p class="user-name"> <%= user.first_name + " " + user.last_name %> </p>
      <p class="user-email"> <%= user.email %> </p>
      <p class="user-phone"> <%= user.phone_no %> </p>
      <% if role == "clerk" %>
        <%= form_with(url: "/users/#{user.id}/removeAsClerk", method: "post") do %>
          <%= submit_tag("Remove As Clerk", class: "user-change-role", data: { disable_with: "Removing.." }) %>
        <% end %>
      <% elsif role != "owner" %>
        <%= form_with(url: "/users/#{user.id}/makeAsClerk", method: "post") do %>
          <%= submit_tag("Appoint As Clerk", class: "user-change-role", data: { disable_with: "Appointing.." }) %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>
</section>

app/views/users/index.html.erb
<article>
<%= render partial: "users", locals: { role: "clerk" } %>
<%= render partial: "users", locals: { role: "customer" } %>
<%= render partial: "users", locals: { role: "owner" } %>
</article>

app/views/users/new.html.erb
<section class="UserNew">
  <p class="NewUsers-title">Welcome new user!</p>
  <p class="FormInput-label">Already have an account? <%= link_to "Sign In", new_sessions_path %></p>
  <%= form_with url: users_path do |form| %>
    <div class="Form-section">
      <p class="FormInput-label">First name:</p>
      <%= form.text_field :first_name, class: "Form-input", autofocus: true %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Last name:</p>
      <%= form.text_field :last_name, class: "Form-input" %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Email:</p>
      <%= form.email_field :email, class: "Form-input" %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Phone Number:</p>
      <%= form.phone_field :phone_no, class: "Form-input" %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Password:</p>
      <%= form.password_field :password, class: "Form-input" %>
    </div>
    <div class="Form-section">
      <%= form.submit "SIGN UP", class: "Form-submit" %>
    </div>
  <% end %>
</section>

app/views/users/new_clerk.html.erb
<section class="UserNew">
  <p class="NewUsers-title">Create a clerk/owner account!</p>
  <%= form_with url: "/users/create_clerk", method: "post" do |form| %>
    <div class="Form-section">
      <%= form.select :user_role, options_for_select(["clerk", "owner"]), class: "Form-input" %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">First name:</p>
      <%= form.text_field :first_name, class: "Form-input", autofocus: true %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Last name:</p>
      <%= form.text_field :last_name, class: "Form-input" %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Email:</p>
      <%= form.email_field :email, class: "Form-input" %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Phone Number:</p>
      <%= form.phone_field :phone_no, class: "Form-input" %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Password:</p>
      <%= form.password_field :password, class: "Form-input" %>
    </div>
    <div class="Form-section">
      <%= form.submit "CREATE", class: "Form-submit" %>
    </div>
  <% end %>
</section>